# Generated by Django 4.2.3 on 2023-07-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('description', models.TextField(default='')),
                ('category', models.CharField(choices=[('AG', 'Action Games'), ('AD', 'Adventure Games'), ('HG', 'Horror Games'), ('SG', 'Survival Games'), ('ZG', 'Zombie Games')], max_length=2)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
