# Generated by Django 4.2.3 on 2023-07-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Product',
            new_name='GameProduct',
        ),
    ]
